name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo add-apt-repository -y ppa:fish-shell/nightly-master
          sudo apt-get update
          sudo apt-get -y install fish
      - run: |
          curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
          fisher -v && fisher -h
